using Sloop.Workstation;
static void Check(bool value,string name){if(!value)throw new Exception(name);}
List<MidiChannelMessage> messages=[];
var decoder=new MidiInputDecoder(messages.Add);
decoder.Feed([0x90,60]);decoder.Feed([0xf8,91,61,0,0xf0,1,2]);decoder.Feed([0xf7,62,80,0x80,60,5]);
Check(messages.SequenceEqual(new MidiChannelMessage[]{new(0x90,60,91),new(0x90,61,0),new(0x80,60,5)}),"fragment, running status, realtime, sysex");
decoder.Reset();decoder.Feed([60,90,0xc1,8,9,0xf2,1,2,0x91,65,73]);
Check(messages.TakeLast(3).SequenceEqual(new MidiChannelMessage[]{new(0xc1,8,0),new(0xc1,9,0),new(0x91,65,73)}),"system common clears running status");
List<byte[]> output=[];using var player=new PerformancePlayer(output.Add);
var input=new ExternalMidiNotes((owner,pitch,velocity)=>player.Hold(owner,[new(0,pitch)],velocity,PlayStyle.Block),player.Release);
player.Hold("touch",[new(0,60)],100,PlayStyle.Block);
input.Receive(new(0x90,60,78));input.Receive(new(0x90,60,90));input.Receive(new(0x90,60,0));
Check(output.Count==1,"repeated and touch share pitch");
input.Receive(new(0xb0,64,127));input.Receive(new(0x80,60,0));player.Release("touch");
Check(output.Count==1,"sustain retains source ownership after touch release");
input.Receive(new(0xb0,64,0));Check(output.Count==2&&output[^1][0]==0x80,"pedal releases balanced note");
input.Receive(new(0x91,61,43));Check(output[^1][2]==43,"velocity preserved");
input.Receive(new(0x90,61,94));input.Receive(new(0xb1,123,0));Check(player.Active,"other source channel retains shared note");
input.Receive(new(0xb0,120,0));Check(!player.Active,"all sound off");
input.Receive(new(0x90,62,70));input.Receive(new(0xb0,64,127));input.Receive(new(0x80,62,0));input.Receive(new(0xb0,121,0));Check(!player.Active,"reset controllers releases sustained notes");
input.Receive(new(0x90,64,80));input.Reset();input.Receive(new(0x80,64,0));Check(!player.Active&&input.Count==0,"disconnect reset and stale release");
Check(ExternalMidiHarmony.Chord(60,0,PerformanceScale.Major,ChordShape.Diatonic,0)!.Notes.SequenceEqual(new[]{60,64,67}),"root register");
Check(ExternalMidiHarmony.Chord(61,0,PerformanceScale.Major,ChordShape.Diatonic,0) is null,"chromatic roots ignored");
Check(ExternalMidiHarmony.Chord(62,2,PerformanceScale.Major,ChordShape.Seventh,0)!.Notes.SequenceEqual(new[]{62,66,69,73}),"key and seventh");
Console.WriteLine("External MIDI decoder, ownership, sustain, channel cancellation and harmony checks passed.");
var wire=new System.Collections.Concurrent.ConcurrentQueue<byte[]>();using var timed=new PerformancePlayer(wire.Enqueue);
var timedInput=new ExternalMidiNotes((owner,pitch,velocity)=>timed.Hold(owner,[new(0,pitch),new(0,pitch+4)],velocity,PlayStyle.StrumUp,strumMs:200),timed.Release);
timedInput.Receive(new(0x90,60,82));
for(int i=0;i<100&&!wire.Any();i++)await Task.Delay(5);
Check(wire.Any(),"timed job begins");timedInput.Reset();await Task.Delay(250);
Check(wire.Count(b=>b[0]==0x90)==wire.Count(b=>b[0]==0x80)&&!wire.Any(b=>b[0]==0x90&&b[1]==64),"disconnect cancels pending strum with balanced output");
Console.WriteLine("Timed controller cancellation passed.");
