using Sloop.Android;
using Sloop.Sequencing;

int checks = 0;
void Check(bool value, string name) { if (!value) throw new Exception(name); checks++; }
void Reject(Action action, string name) { try { action(); } catch (EditException) { checks++; return; } throw new Exception(name); }
AppPattern Empty() => new(Guid.NewGuid(), Guid.NewGuid(), 960, new(15360), []);
EditProposal? Gesture(PianoRollModel m, AppPattern p, double x, double y, double endX, double endY)
{ m.Begin(p, 0, x, y, 480, 288, 100, 240); return m.End(endX, endY, 8, 48); }
var empty = Empty();
var model = new PianoRollModel { Tool = PianoRollTool.Draw };
Check(Gesture(model, empty, 30, 24, 60, 24) is null && empty.Notes.Length == 0, "Draw drag must not insert");
model.Begin(empty, 0, 30, 24, 480, 288, 100, 240); model.Cancel();
Check(model.End(30, 24, 8, 48) is null, "Cancel must not insert");
var creation = Gesture(model, empty, 30, 24, 30, 24)!;
var history = new EditHistory(empty); history.Apply(creation);
var pattern = (AppPattern)history.Current; var note = pattern.Notes.Single();
Check(note.Start.Value == 240 && note.Pitch == 65 && note.Channel == 0 && note.Duration.Value == 240, "Tap creates quantized note");
Check(model.Selected == note.Id, "Created identity selected");
Check(Gesture(model, pattern, 65, 24, 65, 24) is null, "Draw over note selects without duplicate");
model.Tool = PianoRollTool.Move;
model.Begin(pattern, 0, 60, 24, 480, 288, 100, 240); model.Update(120, 72, 8);
Check(model.Preview?.Start.Value == 480 && model.Preview.Pitch == 64 && pattern.Notes.Single() == note, "Preview leaves source untouched");
var move = model.End(120, 72, 8, 48)!; history.Apply(move);
pattern = (AppPattern)history.Current;
Check(pattern.Notes.Single().Id == note.Id && pattern.Notes.Single().Pitch == 64, "Move preserves identity");
history.Undo(); Check(((AppPattern)history.Current).Notes.Single() == note, "One gesture undo");
history.Redo(); pattern = (AppPattern)history.Current;
Check(pattern.Notes.Single().Start.Value == 480, "Redo move");
model.Tool = PianoRollTool.Resize;
history.Apply(Gesture(model, pattern, 120, 72, 240, 72)!); pattern = (AppPattern)history.Current;
Check(pattern.Notes.Single().Duration.Value == 720, "Resize duration");
history.Apply(Gesture(model, pattern, 240, 72, -1000, 72)!); pattern = (AppPattern)history.Current;
Check(pattern.Notes.Single().Duration.Value == 240, "Minimum duration");
history.Apply(Gesture(model, pattern, 60, 72, 100000, 72)!); pattern = (AppPattern)history.Current;
Check(pattern.Notes.Single().Start.Value + pattern.Notes.Single().Duration.Value == pattern.Length.Value, "Resize phrase boundary");
model.ProtectSelected(true);
Reject(() => model.Delete(pattern), "Protected delete rejected");
Reject(() => Gesture(model, pattern, 60, 72, -100, 72), "Protected resize rejected");
Check(model.Preview is null, "Rejected edit clears preview");
model.Tool = PianoRollTool.Move;
Reject(() => Gesture(model, pattern, 60, 72, 60, 24), "Protected pitch move rejected");
model.ProtectSelected(false);
var delete = model.Delete(pattern); history.Apply(delete);
Check(((AppPattern)history.Current).Notes.IsEmpty, "Delete selected"); history.Undo();
Check(((AppPattern)history.Current).Notes.Single().Id == note.Id, "Delete undo identity");
Reject(() => history.Apply(delete), "Stale source rejects");
model.Tool = PianoRollTool.Pan;
var before = history.Current;
Check(Gesture(model, (AppPattern)before, 240, 144, -240, 96) is null && model.Left == 1920 && model.TopPitch == 64, "Pan viewport without proposal");
Check(ReferenceEquals(history.Current, before), "Pan no history");
model.Navigate(100000, 1000, 15360);
Check(model.Left + model.Span == 15360 && model.TopPitch == 127, "Viewport upper bounds");
model.Navigate(-100000, -1000, 15360);
Check(model.Left == 0 && model.TopPitch == 5, "Viewport lower bounds");
model.Zoom(.5, 15360); Check(model.Span == 960, "Zoom in");
model.Zoom(1000, 15360); Check(model.Span == 15360 && model.Left == 0, "Zoom phrase bounds");
Check(model.Snap(120) == 240 && model.Snap(-120) == 0, "Half-grid rounds forward");
// Expanded finger target still prefers a literal note if short adjacent notes compete.
var a = note with { Start = new(0), Duration = new(30) };
var b = note with { Id = Guid.NewGuid(), Start = new(60), Duration = new(30) };
pattern = empty with { Notes = [a, b] };
var hitModel = new PianoRollModel();
Check(hitModel.Hit(pattern, 0, 17, 24, 480, 288, 48) == b.Id, "Literal hit precedence");
Check(hitModel.Hit(pattern, 1, 17, 24, 480, 288, 48) is null, "Channel isolation");
model = new PianoRollModel { Tool = PianoRollTool.Select };
Check(Gesture(model, pattern, 17, 24, 17, 24) is null && model.Selected == b.Id, "Selection no edit");
var offGrid = b with { Start = new(120) }; pattern = empty with { Notes = [a, offGrid] };
model.Selected = b.Id; model.ProtectSelected(true);
Reject(() => model.Quantize(pattern), "Protected quantize rejected");
model.ProtectSelected(false); var quantized = (AppPattern)model.Quantize(pattern).After;
Check(quantized.Notes.Single(n => n.Id == b.Id).Start.Value == 240 && quantized.Notes.Single(n => n.Id == a.Id) == a, "Selected quantize preserves other notes");
model.Reconcile(empty, 0); Check(model.Selected is null, "Stale selection cleared");
model.Selected=b.Id;model.ProtectSelected(true);model.Reconcile(empty,0);model.Reconcile(pattern,0);
Check(model.Locks.Events.Contains(b.Id),"Protection survives temporarily absent undo contents");
model.ResetWorkspace();Check(model.Selected is null && model.Locks.Events.IsEmpty && model.Locks.Parts.IsEmpty,"Workspace adoption resets local protection");
model = new PianoRollModel { Tool = PianoRollTool.Draw };
model.SetLocks(new([empty.Id], []));
Reject(() => Gesture(model, empty, 240, 24, 240, 24), "Protected part insertion rejects");
model.SetLocks(EditLocks.None);
var otherChannel = a with { Id = Guid.NewGuid(), Channel = 9 };
pattern = empty with { Notes = [a, b, otherChannel] };
model.Tool = PianoRollTool.Move; model.Selected = b.Id;
var bounded = (AppPattern)Gesture(model, pattern, 240, 144, -100000, -100000)!.After;
Check(bounded.Notes.Single(n => n.Id == b.Id).Start.Value == 0 && bounded.Notes.Single(n => n.Id == b.Id).Pitch == 127, "Move start and pitch bounds");
Check(bounded.Notes.Single(n => n.Id == a.Id) == a && bounded.Notes.Single(n => n.Id == otherChannel.Id) == otherChannel, "Move preserves unselected and other channels");
var right = (AppPattern)Gesture(model, pattern, 240, 144, 100000, 100000)!.After;
Check(right.Notes.Single(n => n.Id == b.Id).Start.Value == pattern.Length.Value - b.Duration.Value && right.Notes.Single(n => n.Id == b.Id).Pitch == 0, "Move end and pitch bounds");
model.Begin(pattern, 0, 240, 144, 480, 288, 100, 240); model.Update(360, 144, 8); model.Cancel();
Check(model.End(360, 144, 8, 48) is null && model.Preview is null, "Canceled drag drops preview");
var custom = empty with { TicksPerQuarter = 480, Length = new(1920) };
model = new PianoRollModel { Tool = PianoRollTool.Draw, Grid = 120 };
model.Reconcile(custom, 0);
var customNote = ((AppPattern)Gesture(model, custom, 480, 24, 480, 24)!.After).Notes.Single();
Check(customNote.Start.Value == 1800 && customNote.Duration.Value == 120, "Custom PPQ and phrase-end insertion");
Check(Gesture(model,custom,-1,24,-1,24) is null,"Out-of-bounds touch cannot create edge note");
Check(Gesture(model,custom,480,24,481,24) is null,"Release outside roll cannot create edge note");
Check(Gesture(model,custom,240,24,double.NaN,24) is null,"Invalid touch cancels safely");
model.Begin(custom,0,10,10,0,288,100,120);
Check(model.End(10,10,8,48) is null,"Zero-sized surface does not begin gesture");
// Group gestures use shared deltas and one history transaction.
var g1 = a with { Start = new(120), Duration = new(240), Pitch = 65 };
var g2 = b with { Start = new(600), Duration = new(480), Pitch = 64 };
var foreign = otherChannel with { Start = new(120), Pitch = 65 };
pattern = empty with { Notes = [g1, g2, foreign] };
model = new PianoRollModel { Tool = PianoRollTool.MultiSelect };
Gesture(model, pattern, 40, 24, 40, 24);
Gesture(model, pattern, 180, 72, 180, 72);
Check(model.SelectedIds.SetEquals(new[] { g1.Id, g2.Id }), "Multi select toggles notes");
Gesture(model, pattern, 40, 24, 40, 24);
Check(model.SelectedIds.SetEquals(new[] { g2.Id }), "Multi select toggles off");
model.ClearSelection();
model.Begin(pattern, 0, 0, 0, 480, 288, 100, 240); model.Update(280, 96, 8);
Check(model.SelectionBox is not null && model.SelectedIds.IsEmpty, "Box previews without selection mutation");
model.Cancel(); Check(model.SelectionBox is null && model.SelectedIds.IsEmpty, "Box cancel discards selection");
Check(Gesture(model, pattern, 0, 0, 280, 96) is null && model.SelectedIds.SetEquals(new[] { g1.Id, g2.Id }), "Box selects intersecting notes on edit channel");
model.Tool = PianoRollTool.Move;
model.Begin(pattern, 0, 240, 144, 480, 288, 100, 240); model.Update(-100000, -100000, 8);
Check(model.Previews.Length == 2 && pattern.Notes[0] == g1, "Group preview is immutable");
var groupMove = model.End(-100000, -100000, 8, 48)!;
var movedGroup = (AppPattern)groupMove.After;
Check(movedGroup.Notes.Single(n => n.Id == g1.Id).Start.Value == 0 && movedGroup.Notes.Single(n => n.Id == g2.Id).Start.Value == 480, "Group move keeps onset spacing at left bound");
Check(movedGroup.Notes.Single(n => n.Id == g1.Id).Pitch == 127 && movedGroup.Notes.Single(n => n.Id == g2.Id).Pitch == 126, "Group move keeps pitch spacing at MIDI bound");
Check(movedGroup.Notes.Single(n => n.Id == foreign.Id) == foreign && groupMove.Changes.Length == 2, "Group preserves other channels");
history = new EditHistory(pattern); history.Apply(groupMove); history.Undo();
Check(((AppPattern)history.Current).Notes.SequenceEqual(pattern.Notes) && !history.CanUndo, "Group move has one atomic undo");
history.Redo(); Check(((AppPattern)history.Current).Notes.SequenceEqual(movedGroup.Notes), "Group redo restores all notes");
Reject(() => history.Apply(groupMove), "Group stale proposal rejects");
model.SetLocks(new([], [g2.Id]));
Reject(() => Gesture(model, pattern, 240, 144, 300, 144), "One protected member rejects complete group move");
Reject(() => model.Delete(pattern), "One protected member rejects complete group deletion");
Check(pattern.Notes.SequenceEqual(new[] { g1, g2, foreign }) && model.Previews.IsEmpty, "Rejected group leaves source intact and clears preview");
model.SetLocks(new([g2.PartId], []));
Reject(() => Gesture(model, pattern, 240, 144, 300, 144), "Part protection rejects group");
model.SetLocks(EditLocks.None); model.Tool = PianoRollTool.Resize;
Check(Gesture(model, pattern, 240, 144, -100000, 144) is null, "Resize shared minimum bound keeps duration difference without history");
var resized = (AppPattern)Gesture(model, pattern, 240, 144, 100000, 144)!.After;
Check(resized.Notes.Single(n => n.Id == g2.Id).Start.Value + resized.Notes.Single(n => n.Id == g2.Id).Duration.Value == pattern.Length.Value && resized.Notes.Single(n => n.Id == g2.Id).Duration.Value - resized.Notes.Single(n => n.Id == g1.Id).Duration.Value == 240, "Group resize shares phrase bound");
var groupQuantize = model.Quantize(pattern);
Check(((AppPattern)groupQuantize.After).Notes.Single(n => n.Id == g1.Id).Start.Value == 240 && ((AppPattern)groupQuantize.After).Notes.Single(n => n.Id == g2.Id).Start.Value == 720 && groupQuantize.Changes.Length == 2, "Group quantize rounds each onset forward");
model.SetLocks(new([], [g2.Id])); Reject(() => model.Quantize(pattern), "Group quantize honors shared protections");
model.SetLocks(EditLocks.None); model.ProtectSelected(true);
Check(model.SelectedIds.All(model.Locks.Events.Contains), "Protection covers entire selection");
model.ProtectSelected(false); history = new EditHistory(pattern); history.Apply(model.Delete(pattern));
Check(((AppPattern)history.Current).Notes.SequenceEqual(new[] { foreign }), "Group deletion preserves unselected channel");
history.Undo(); Check(((AppPattern)history.Current).Notes.SequenceEqual(pattern.Notes), "Group delete atomic undo");
model.Reconcile(pattern, 9); Check(model.SelectedIds.IsEmpty, "Channel switch reconciles group selection");
model.SelectAll(pattern, 0); Check(model.SelectedIds.Count == 2, "Select all scoped to edit channel");
model.ResetWorkspace(); Check(model.SelectedIds.IsEmpty, "Workspace reset clears group selection");
// App notes permit overlaps; group operations retain the existing app-domain collision policy.
model.SelectAll(pattern, 0); model.Tool = PianoRollTool.Move;
var overlapPattern = pattern with { Notes = [g1, g2 with { Pitch = 65, Start = new(120) }, foreign] };
Check(((AppPattern)Gesture(model, overlapPattern, 240, 144, 300, 144)!.After).Notes.Length == 3, "Existing legal app overlaps remain legal");
// Short imported notes retain their relative durations; a grid must not lengthen them on a left drag.
var shortGroup = pattern with { Notes = [g1 with { Duration = new(30) }, g2 with { Duration = new(90) }, foreign] };
model.SelectAll(shortGroup, 0); model.Tool = PianoRollTool.Resize;
Check(Gesture(model, shortGroup, 240, 144, -100000, 144) is null, "Subgrid group cannot shrink a short member below its imported duration");
var shortResize = Gesture(model, shortGroup, 240, 144, 300, 144)!;
var shortAfter = (AppPattern)shortResize.After;
Check(shortAfter.Notes.Single(n => n.Id == g1.Id).Duration.Value == 270 && shortAfter.Notes.Single(n => n.Id == g2.Id).Duration.Value == 330, "Subgrid group grows by one shared grid delta");
history = new EditHistory(shortGroup); history.Apply(shortResize); history.Undo();
Check(((AppPattern)history.Current).Notes.SequenceEqual(shortGroup.Notes) && !history.CanUndo, "Group resize undo restores short durations atomically");
history.Redo(); Check(((AppPattern)history.Current).Notes.SequenceEqual(shortAfter.Notes), "Group resize redo restores all durations");
// Protecting a later member must reject after earlier members have been staged, without partial adoption.
model.SetLocks(new([], [g2.Id]));
Reject(() => Gesture(model, shortGroup, 240, 144, 300, 144), "Group resize rejects a protected later member");
Check(model.Previews.IsEmpty && shortGroup.Notes.Single(n => n.Id == g1.Id).Duration.Value == 30, "Late resize rejection clears previews and leaves source unchanged");
model.SetLocks(EditLocks.None);
// A new channel/source invalidates the capture even when no Android detach event has arrived yet.
model.Tool = PianoRollTool.Move; model.SelectAll(pattern, 0);
model.Begin(pattern, 0, 240, 144, 480, 288, 100, 240); model.Update(300, 144, 8);
model.Reconcile(pattern, 9);
Check(model.End(300, 144, 8, 48) is null && model.Previews.IsEmpty && model.SelectedIds.IsEmpty, "Channel switch cancels old group gesture before release");
model.SelectAll(pattern, 0); model.Begin(pattern, 0, 240, 144, 480, 288, 100, 240); model.Update(300, 144, 8);
model.Reconcile(pattern with { Revision = Guid.NewGuid() }, 0);
Check(model.End(300, 144, 8, 48) is null && model.Previews.IsEmpty, "Source adoption cancels an old group gesture before release");
model.Begin(pattern, 0, 240, 144, 480, 288, 100, 240); model.Update(300, 144, 8); model.Reconcile(pattern, 0);
Check(model.End(300, 144, 8, 48) is not null, "Same-source reconciliation retains valid gesture");
model.Begin(pattern, 0, 240, 144, 480, 288, 100, 240); model.Update(300, 144, 8);
Check(model.End(double.PositiveInfinity, 144, 8, 48) is null && model.Previews.IsEmpty, "Nonfinite group release cancels all previews");
// Clamping at the opposite edges preserves group timing and pitch intervals.
model.SelectAll(pattern, 0);
var farRight = (AppPattern)Gesture(model, pattern, 240, 144, 100000, 100000)!.After;
var rightFirst = farRight.Notes.Single(n => n.Id == g1.Id); var rightSecond = farRight.Notes.Single(n => n.Id == g2.Id);
Check(rightSecond.Start.Value + rightSecond.Duration.Value == pattern.Length.Value && rightSecond.Start.Value - rightFirst.Start.Value == 480 && rightFirst.Pitch == 1 && rightSecond.Pitch == 0, "Group right and low bounds preserve intervals");
model.Tool = PianoRollTool.MultiSelect; model.Selected = g1.Id;
Gesture(model, pattern, 280, 96, 140, 48);
Check(model.SelectedIds.SetEquals(new[] { g1.Id, g2.Id }), "Reverse box adds to existing selection without replacing it");
model.Begin(pattern, 0, 0, 0, 480, 288, 100, 240); model.Update(280, 96, 8); model.Cancel();
Check(model.SelectedIds.SetEquals(new[] { g1.Id, g2.Id }) && model.SelectionBox is null, "Canceled box preserves existing selected identities");
model.Tool = PianoRollTool.Move; model.Begin(pattern, 0, 240, 144, 480, 288, 100, 240); model.Update(300, 144, 8);
model.SetLocks(new([], [g2.Id]));
Reject(() => model.End(300, 144, 8, 48), "Protection added during drag is enforced at release");
Check(model.Previews.IsEmpty && model.SelectedIds.Count == 2, "Release rejection clears transient preview but retains selection");
model.SetLocks(EditLocks.None); history = new EditHistory(pattern); history.Apply(model.Quantize(pattern)); history.Undo();
Check(((AppPattern)history.Current).Notes.SequenceEqual(pattern.Notes) && !history.CanUndo, "Group quantize is one undo transaction");
Console.WriteLine($"Piano roll: {checks} focused checks passed.");
